name: Deploy API
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: myst-templates/.github
          path: readme
          token: ${{ secrets.PAT }}
      - run: npm install
      - run: npm run build:cli
      - run: npm run link
      - name: Clone and index templates
        run: myst-templates-api index data/tex.yml data/docx.yml data/site.yml
      - run: npm run build
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Update organization readme
        run: |
          cd readme
          git config --local user.name 'myst-templates[bot]'
          git config --local user.email 'myst-templates[bot]@users.noreply.github.com'
          git commit profile/README.md -m '📖 Update templates table' || echo "🧹 No changes!"
          git push origin || echo "🧹 No changes!"
